language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: 4kuCakNmKTPAGwrZd1pFFf2pdfGFYQniW1V0z4M5/gaLoElJasydwZyP2N9F6O/SaXEaB/sB0a+aFUP2U5t6QgB+Oq5YtyIGQlmHfj1x3ztXgiLFpkJvC2WGDHmZXpo69jTA0m4IdmReQxr84HLG90/g4R+HlQDFDmness0XQpgd48I1w/quDuWxm0Lj6dCjfpjq5SLvkMjuuvPhj6hX+aYeRs4cZXL+KvkLPFECmL7oJKCFmNQ5SekqSf/tdfgyRCbnDd0lCg7bu6SyQnHgG4aegDcItRA2p8COaFaYHdUgVFMCC9LSn98mu2WEVwOe146h7ESzh5aGWojM9hiHgtidmiyxavLTKoAoSudCZ+AYOpXcMu1OR2ylO9PTZ+iwSmM4s7Z4SQyGiESCirwsmTg1Y7yZI/bFQ0jW5cvDEkEYyd2/cVX8aoMTi0gaqCfbay4azx7/zDc6igPPeNcBuKdRn6qOnYeuxv8xRls+BJvSehQ1NDG2WaEqoJteqfEAzqAWpcW6HQf72ZT3V8w3djHV150ifu6TMGzXWIkQK5LcPqp1HhLnGcHKBUatqGBCiu+5pU4A36cOUyUMkW7eAuh3iYh6UgQCuLu/U3Rv27EM3kA0QSr9ooZX19Rv+dJNLwry3KKFJW5me/0150+9fZ0xgZNST0D+s5HOJ/qY9h8=
  app: shrouded-forest-74612
  on:
    repo: jwoleslagle/node-shopping-list-integration-tests
